# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vagrant/code/cpp-ethereum/libethash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vagrant/code/cpp-ethereum/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vagrant/code/cpp-ethereum/build/CMakeFiles /home/vagrant/code/cpp-ethereum/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vagrant/code/cpp-ethereum/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ethash

# Build rule for target.
ethash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ethash
.PHONY : ethash

# fast build rule for target.
ethash/fast:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/build
.PHONY : ethash/fast

# target to build an object file
internal.o:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/internal.o
.PHONY : internal.o

# target to preprocess a source file
internal.i:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/internal.i
.PHONY : internal.i

# target to generate assembly for a file
internal.s:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/internal.s
.PHONY : internal.s

# target to build an object file
io.o:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/io.o
.PHONY : io.o

# target to preprocess a source file
io.i:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/io.i
.PHONY : io.i

# target to generate assembly for a file
io.s:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/io.s
.PHONY : io.s

# target to build an object file
io_posix.o:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/io_posix.o
.PHONY : io_posix.o

# target to preprocess a source file
io_posix.i:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/io_posix.i
.PHONY : io_posix.i

# target to generate assembly for a file
io_posix.s:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/io_posix.s
.PHONY : io_posix.s

# target to build an object file
sha3.o:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/sha3.o
.PHONY : sha3.o

# target to preprocess a source file
sha3.i:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/sha3.i
.PHONY : sha3.i

# target to generate assembly for a file
sha3.s:
	$(MAKE) -f CMakeFiles/ethash.dir/build.make CMakeFiles/ethash.dir/sha3.s
.PHONY : sha3.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ethash"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... internal.o"
	@echo "... internal.i"
	@echo "... internal.s"
	@echo "... io.o"
	@echo "... io.i"
	@echo "... io.s"
	@echo "... io_posix.o"
	@echo "... io_posix.i"
	@echo "... io_posix.s"
	@echo "... sha3.o"
	@echo "... sha3.i"
	@echo "... sha3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

